// <auto-generated />
using System;
using EstateAgency.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstateAgency.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121074238_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EstateAgency.Domain.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CounterpartyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("RealEstateId")
                        .HasColumnType("int");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("RealEstateId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CounterpartyId = 1,
                            Date = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 1,
                            TransactionAmount = 8000000m,
                            Type = "Sell"
                        },
                        new
                        {
                            Id = 2,
                            CounterpartyId = 2,
                            Date = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 2,
                            TransactionAmount = 12500000m,
                            Type = "Buy"
                        },
                        new
                        {
                            Id = 3,
                            CounterpartyId = 3,
                            Date = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 3,
                            TransactionAmount = 5200000m,
                            Type = "Sell"
                        },
                        new
                        {
                            Id = 4,
                            CounterpartyId = 4,
                            Date = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 4,
                            TransactionAmount = 9800000m,
                            Type = "Buy"
                        },
                        new
                        {
                            Id = 5,
                            CounterpartyId = 5,
                            Date = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 5,
                            TransactionAmount = 18000000m,
                            Type = "Sell"
                        },
                        new
                        {
                            Id = 6,
                            CounterpartyId = 1,
                            Date = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 6,
                            TransactionAmount = 15300000m,
                            Type = "Buy"
                        },
                        new
                        {
                            Id = 7,
                            CounterpartyId = 2,
                            Date = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 7,
                            TransactionAmount = 6700000m,
                            Type = "Sell"
                        },
                        new
                        {
                            Id = 8,
                            CounterpartyId = 3,
                            Date = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 8,
                            TransactionAmount = 3500000m,
                            Type = "Buy"
                        },
                        new
                        {
                            Id = 9,
                            CounterpartyId = 1,
                            Date = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 9,
                            TransactionAmount = 10100000m,
                            Type = "Sell"
                        },
                        new
                        {
                            Id = 10,
                            CounterpartyId = 2,
                            Date = new DateTime(2024, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RealEstateId = 10,
                            TransactionAmount = 7900000m,
                            Type = "Buy"
                        });
                });

            modelBuilder.Entity("EstateAgency.Domain.Entities.Counterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Counterparties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Ivan Ivanov",
                            PassportNumber = "4500 123456",
                            PhoneNumber = "+7 999 111-22-33"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Maria Petrova",
                            PassportNumber = "4501 654321",
                            PhoneNumber = "+7 999 222-33-44"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Sergey Sidorov",
                            PassportNumber = "4502 789012",
                            PhoneNumber = "+7 999 333-44-55"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Ekaterina Kozlova",
                            PassportNumber = "4503 345678",
                            PhoneNumber = "+7 999 444-55-66"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Dmitry Volkov",
                            PassportNumber = "4504 901234",
                            PhoneNumber = "+7 999 555-66-77"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Anna Smirnova",
                            PassportNumber = "4505 112233",
                            PhoneNumber = "+7 999 666-77-88"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Pavel Novikov",
                            PassportNumber = "4506 445566",
                            PhoneNumber = "+7 999 777-88-99"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Olga Kuznetsova",
                            PassportNumber = "4507 778899",
                            PhoneNumber = "+7 999 888-99-00"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Mikhail Lebedev",
                            PassportNumber = "4508 556677",
                            PhoneNumber = "+7 999 999-00-11"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Elena Morozova",
                            PassportNumber = "4509 334455",
                            PhoneNumber = "+7 999 000-11-22"
                        });
                });

            modelBuilder.Entity("EstateAgency.Domain.Entities.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<double?>("CeilingHeight")
                        .HasColumnType("double");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Floors")
                        .HasColumnType("int");

                    b.Property<bool>("IsEncumbrance")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Rooms")
                        .HasColumnType("int");

                    b.Property<float>("Square")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RealEstates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Ленина, д. 15, кв. 34",
                            CadastralNumber = "12:34:5678912:3456",
                            CeilingHeight = 270.0,
                            FloorNumber = 3,
                            Floors = 5,
                            IsEncumbrance = false,
                            Purpose = "Residential",
                            Rooms = 2,
                            Square = 65.5f,
                            Type = "Apartment"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Садовая, д. 42",
                            CadastralNumber = "23:45:6789012:7890",
                            CeilingHeight = 280.0,
                            FloorNumber = 1,
                            Floors = 2,
                            IsEncumbrance = true,
                            Purpose = "Residential",
                            Rooms = 4,
                            Square = 120.8f,
                            Type = "House"
                        },
                        new
                        {
                            Id = 3,
                            Address = "пр. Мира, д. 88, оф. 305",
                            CadastralNumber = "34:56:7890123:123",
                            CeilingHeight = 300.0,
                            FloorNumber = 3,
                            Floors = 10,
                            IsEncumbrance = false,
                            Purpose = "Commercial",
                            Rooms = 1,
                            Square = 45.2f,
                            Type = "Office"
                        },
                        new
                        {
                            Id = 4,
                            Address = "пос. Дачный, ул. Центральная, д. 7",
                            CadastralNumber = "45:67:8901234:56789",
                            CeilingHeight = 290.0,
                            FloorNumber = 1,
                            Floors = 1,
                            IsEncumbrance = false,
                            Purpose = "Residential",
                            Rooms = 3,
                            Square = 95f,
                            Type = "Cottage"
                        },
                        new
                        {
                            Id = 5,
                            Address = "промзона, складской комплекс №5",
                            CadastralNumber = "56:78:9012345:1",
                            CeilingHeight = 400.0,
                            FloorNumber = 1,
                            Floors = 1,
                            IsEncumbrance = true,
                            Purpose = "Industrial",
                            Rooms = 0,
                            Square = 500f,
                            Type = "Warehouse"
                        },
                        new
                        {
                            Id = 6,
                            Address = "ул. Парковая, д. 25",
                            CadastralNumber = "67:89:0123456:999999",
                            CeilingHeight = 275.0,
                            FloorNumber = 2,
                            Floors = 3,
                            IsEncumbrance = false,
                            Purpose = "Residential",
                            Rooms = 5,
                            Square = 145f,
                            Type = "Townhouse"
                        },
                        new
                        {
                            Id = 7,
                            Address = "ТЦ 'Европа', 1 этаж, пав. 12",
                            CadastralNumber = "78:90:1234567:88",
                            CeilingHeight = 320.0,
                            FloorNumber = 1,
                            Floors = 3,
                            IsEncumbrance = false,
                            Purpose = "Commercial",
                            Rooms = 1,
                            Square = 85.3f,
                            Type = "Shop"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Гаражный кооператив 'Мотор', бокс 15",
                            CadastralNumber = "89:01:2345678:0",
                            CeilingHeight = 250.0,
                            FloorNumber = 1,
                            Floors = 1,
                            IsEncumbrance = true,
                            Purpose = "Commercial",
                            Rooms = 0,
                            Square = 25f,
                            Type = "Garage"
                        },
                        new
                        {
                            Id = 9,
                            Address = "пр. Победы, д. 112, кв. 89",
                            CadastralNumber = "90:12:3456789:123456789",
                            CeilingHeight = 265.0,
                            FloorNumber = 9,
                            Floors = 12,
                            IsEncumbrance = false,
                            Purpose = "Residential",
                            Rooms = 3,
                            Square = 78.2f,
                            Type = "Apartment"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Бизнес-центр 'Старт', оф. 405",
                            CadastralNumber = "01:23:4567890:4567",
                            CeilingHeight = 310.0,
                            FloorNumber = 4,
                            Floors = 8,
                            IsEncumbrance = true,
                            Purpose = "Commercial",
                            Rooms = 2,
                            Square = 67.8f,
                            Type = "Office"
                        });
                });

            modelBuilder.Entity("EstateAgency.Domain.Entities.Application", b =>
                {
                    b.HasOne("EstateAgency.Domain.Entities.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstateAgency.Domain.Entities.RealEstate", null)
                        .WithMany()
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
