<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.2.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0ce6db6a-390b-439b-9097-dd871f253596</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.0.0" />
    <PackageReference Include="Aspire.Hosting.MySql" Version="13.0.0" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.0.0" />
    <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EstateAgency.Api\EstateAgency.Api.csproj" />
  </ItemGroup>

</Project>
